### ISSUE TITLE
Any Example with WriteData

### ISSUE THREAD

**Issue by bapzangbo** [masroore/CurlSharp#12]
can you write or update an example to write data downloaded to harddisk.
Thanks

**Comment by masroore** [comment]
https://github.com/masroore/CurlSharp/blob/master/Samples/EasyGet/EasyGet.cs

**Comment by chucklu** [comment]
easy.WriteData = null;
easy.WriteFunction = OnWriteData;
@masroore  the easyget demo is about WriteFunction not WriteData
