### ISSUE TITLE
Error "SslCaCert"  all https site

### ISSUE THREAD

**Issue by tablesmit** [masroore/CurlSharp#15]
Error "SslCaCert" all https site
sample site
https://www.google.com/
https://www.whatismyreferer.com/
https://www.facebook.com/

**Comment by BroZeus** [comment]
Do this before .Perform() function*(assuming that object name is `easy`)* -- **`easy.SslVerifyPeer = false;`**

**Comment by tablesmit** [comment]
Thank you so much BroZeus
