### ISSUE TITLE
First push data generate unknown error

### ISSUE THREAD

**Issue by lailongwei** [masroore/CurlSharp#18]
When i first create CurlEasy in non-mainthread, the webserver receive postfields is random, sometimes like 
![image](https://cloud.githubusercontent.com/assets/15770958/15699732/d3382a90-2801-11e6-91bf-abfdfd4dbdda.png)
, some times like 
![image](https://cloud.githubusercontent.com/assets/15770958/15699739/e5e22092-2801-11e6-9dd7-565794e8ed29.png)

This bug I'm fixing

**Comment by masroore** [comment]
merged #20
