### ISSUE TITLE
Suggest Set NoSignal = true When create CurlEasy object

### ISSUE THREAD

**Issue by lailongwei** [masroore/CurlSharp#21]
libcurl in multi-thread will coredump if enabled signal support(libcurl internal use signal to implemented dns query timeout timer), will coredump, because signal mechanism in multi-thread Situation behavior is undefined!
this will lost dns query timeout function, but we can suggest user compiled c-ares support libcurl to restore dns query timeout function.
Just a suggesstion :-)

**Comment by masroore** [comment]
Merged. Thanks @lailongwei
