### ISSUE TITLE
Response code confusion

### ISSUE THREAD

**Issue by joshuasm** [masroore/CurlSharp#43]
Hi,

I have been using the CurlSharp Library for some time now and Ive noticed I get a response code of 200 on a successful HttpGet. I am a bit confused as to what this means exactly other than(from what I can Guess) is the HTTPGET was successful.

I have looked at the enums but haven't found any 200.

do you mind explaining it?

**Comment by masroore** [comment]
cURL HTTP API returns standard [HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

You may also want to peruse [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616.html) for further details.
