### ISSUE TITLE
Request: Example using multi.InfoRead

### ISSUE THREAD

**Issue by pjf** [masroore/CurlSharp#9]
The [documentation on multi transfers](http://curl.haxx.se/libcurl/c/libcurl-multi.html) indicates that `curl_multi_info_read` should be called to retrieve the status of completed transfers.

I cannot for the life of me get this to work (my thread appears to hang), so I'd *love* an example that uses it.

Many, many thanks!

~ Paul

**Comment by masroore** [comment]
@pjf the `InfoRead()` method only works in 32-bit Windows. It relies on the libcurlshim.dll helper DLL. When you're compiling the CurlSharp assembly, please assign `USE_LIBCURLSHIM` as the conditional compilation symbol at the project properties page. You'll find `libcurlshim.dll `​in `libs\i386` folder. Make sure to set your projects to the `x86` platform.

My C/C++ skills are a bit rusty. It'd be excellent if anyone could port the libcurlshim library to WIN64 and mono OSX/LINUX​.

**Comment by pjf** [comment]
Aha! That would explain things. I'm using curlsharp on Mac and Linux platforms.

I've luckily found a work-around (spawning a thread for each CurlEasy), which I'm testing now.

What are your views on having `InfoRead()` throw an exception if we've been compiled without the shim? That means we fail quickly and obviously. (I'm happy to submit the PR if you like, just pre-clearing that it would be merged if I do.)

Thanks again for an awesome library!

~ Paul

**Comment by masroore** [comment]
@pjf A PR would be great! Thanks!
